# Generated by Django 4.2.7 on 2026-01-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_full_name_user_is_email_verified_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
