# Generated by Django 4.2.7 on 2026-01-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=3)),
                ('risk_score', models.IntegerField(blank=True, help_text='AI-calculated risk score 0-100', null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
                'db_table': 'identities',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('license', 'Driver License'), ('tax_cert', 'Tax Certificate')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('front_image_url', models.URLField()),
                ('back_image_url', models.URLField(blank=True, null=True)),
                ('ocr_data', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity.identity')),
            ],
            options={
                'verbose_name': 'Identity Document',
                'verbose_name_plural': 'Identity Documents',
                'db_table': 'identity_documents',
            },
        ),
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selfie_image_url', models.URLField()),
                ('match_score', models.IntegerField(blank=True, help_text='0-100', null=True)),
                ('liveness_score', models.IntegerField(blank=True, help_text='0-100', null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to='identity.identity')),
            ],
            options={
                'verbose_name': 'Face Verification',
                'verbose_name_plural': 'Face Verifications',
                'db_table': 'face_verifications',
            },
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['national_id_number'], name='identities_nationa_6b59e3_idx'),
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(fields=['verification_status'], name='identities_verific_50d21d_idx'),
        ),
    ]
