# Generated by Django 4.2.7 on 2026-01-22 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('accounting_ai', 'Accounting AI'), ('inventory_ai', 'Inventory AI'), ('fraud_ai', 'Fraud AI'), ('cash_flow_ai', 'Cash Flow AI'), ('sales_ai', 'Sales AI'), ('decision_ai', 'Decision AI')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('performance_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact_analysis', models.JSONField(blank=True, default=dict)),
                ('suggested_actions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='core.company')),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'db_table': 'ai_recommendations',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'priority'], name='ai_recommen_company_1ad464_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('cash_flow', 'Cash Flow'), ('sales_forecast', 'Sales Forecast'), ('demand', 'Demand'), ('fraud', 'Fraud'), ('payment', 'Payment')], max_length=50)),
                ('input_data', models.JSONField(default=dict)),
                ('prediction', models.JSONField(default=dict)),
                ('confidence_score', models.IntegerField(help_text='0-100', validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_outcome', models.JSONField(blank=True, help_text='For model learning', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='core.company')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='ai_engine.aimodel')),
            ],
            options={
                'verbose_name': 'AI Prediction',
                'verbose_name_plural': 'AI Predictions',
                'db_table': 'ai_predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'prediction_type', 'created_at'], name='ai_predicti_company_8c4be7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ai_engine.aimodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audit_logs', to='core.company')),
            ],
            options={
                'verbose_name': 'AI Audit Log',
                'verbose_name_plural': 'AI Audit Logs',
                'db_table': 'ai_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='ai_audit_lo_company_3d4f06_idx'), models.Index(fields=['anomaly_detected', 'severity'], name='ai_audit_lo_anomaly_1128fa_idx')],
            },
        ),
    ]
