# Generated by Django 4.2.7 on 2026-01-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_url', models.URLField()),
                ('transcription', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_entities', models.JSONField(blank=True, default=dict)),
                ('executed_action', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to='core.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Command',
                'verbose_name_plural': 'Voice Commands',
                'db_table': 'voice_commands',
                'indexes': [models.Index(fields=['company', 'created_at'], name='voice_comma_company_d6b0f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('excel', 'Excel'), ('audio', 'Audio'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField()),
                ('ocr_extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_classification', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('contract', 'Contract'), ('receipt', 'Receipt'), ('id_card', 'ID Card'), ('tax_cert', 'Tax Certificate'), ('other', 'Other')], max_length=50, null=True)),
                ('linked_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('linked_entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('classified', 'Classified')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'indexes': [models.Index(fields=['company', 'status'], name='documents_company_1c619b_idx'), models.Index(fields=['linked_entity_type', 'linked_entity_id'], name='documents_linked__fbfc49_idx')],
            },
        ),
    ]
