# Generated by Django 4.2.7 on 2026-01-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='matched_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.company'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'date'], name='bank_transa_bank_ac_eb7cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['is_reconciled'], name='bank_transa_is_reco_c49678_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'is_active'], name='bank_accoun_company_83bd98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('company', 'account_number')},
        ),
    ]
