# Generated by Django 4.2.7 on 2026-01-22 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fraud', 'Fraud'), ('theft', 'Theft'), ('damage', 'Damage'), ('non_payment', 'Non Payment'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='AI-calculated', max_length=20, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('legal_risk_score', models.IntegerField(blank=True, help_text='AI-calculated 0-100', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accused_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='identity.identity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.company')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='LegalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=100, unique=True)),
                ('pdf_url', models.URLField()),
                ('hash_signature', models.CharField(help_text='For verification', max_length=255)),
                ('qr_verification_code', models.CharField(max_length=100, unique=True)),
                ('sent_to_authority_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_reports', to='legal.incident')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_reports_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Report',
                'verbose_name_plural': 'Legal Reports',
                'db_table': 'legal_reports',
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('chat_log', 'Chat Log'), ('location', 'Location')], max_length=20)),
                ('file_url', models.URLField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='legal.incident')),
            ],
            options={
                'verbose_name': 'Incident Evidence',
                'verbose_name_plural': 'Incident Evidences',
                'db_table': 'incident_evidences',
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='core.company')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='identity.identity')),
                ('source_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to='legal.incident')),
            ],
            options={
                'verbose_name': 'Blacklist Entry',
                'verbose_name_plural': 'Blacklist Entries',
                'db_table': 'blacklist',
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'status'], name='incidents_company_1bb1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity'], name='incidents_severit_667686_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['status'], name='blacklist_status_234f42_idx'),
        ),
    ]
